import os


class Config:
    SECRET_KEY = os.environ.get("PRINTING_HOUSE_SECRET_KEY")
    SQLALCHEMY_DATABASE_URI = os.environ.get("PRINTING_HOUSE_DATABASE_URL")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
